INSERT INTO PUBLIC.HM_CATEGORY (ID, NAME, PARENT_ID, IS_PARENT)
VALUES (1, '图书、影像、电子书刊', 0, 1);
INSERT INTO PUBLIC.HM_CATEGORY (ID, NAME, PARENT_ID, IS_PARENT)
VALUES (2, '电子书刊', 1, 1);
INSERT INTO PUBLIC.HM_CATEGORY (ID, NAME, PARENT_ID, IS_PARENT)
VALUES (3, '电子书', 2, 0);
INSERT INTO PUBLIC.HM_CATEGORY (ID, NAME, PARENT_ID, IS_PARENT)
VALUES (4, '手机', 0, 1);
INSERT INTO PUBLIC.HM_CATEGORY (ID, NAME, PARENT_ID, IS_PARENT)
VALUES (5, '家用电器', 0, 1);