CREATE TABLE HM_CATEGORY
(
  ID        BIGINT(20)  NOT NULL AUTO_INCREMENT
  COMMENT '类目ID',
  NAME      VARCHAR(20) NOT NULL
  COMMENT '名称',
  PARENT_ID BIGINT(20)  NOT NULL
  COMMENT '父类目ID, 顶级类目为0',
  IS_PARENT TINYINT(1)  NOT NULL
  COMMENT '是否为父节点，0为否，1为是',
  PRIMARY KEY (ID)
);

CREATE TABLE HM_BRAND
(
  ID     BIGINT(20)   NOT NULL AUTO_INCREMENT,
  NAME   VARCHAR(50)  NOT NULL,
  IMAGE  VARCHAR(200) NOT NULL
  COMMENT 'LOGO',
  LETTER CHAR(1)               DEFAULT ''
  COMMENT '首字母',
  PRIMARY KEY (ID)
);

CREATE TABLE HM_CATEGORY_BRAND (
  ID          BIGINT(20) NOT NULL AUTO_INCREMENT,
  CATEGORY_ID BIGINT(20) NOT NULL,
  BRAND_ID    BIGINT(20) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE HM_SPEC_GROUP (
  ID          BIGINT(20)  NOT NULL AUTO_INCREMENT,
  CATEGORY_ID BIGINT(20)  NOT NULL,
  NAME        VARCHAR(30) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE HM_SPEC_PARAM (
  ID          BIGINT(20)  NOT NULL AUTO_INCREMENT,
  CATEGORY_ID BIGINT(20)  NOT NULL,
  GROUP_ID    BIGINT(20)  NOT NULL,
  NAME        VARCHAR(30) NOT NULL,
  UNIT        VARCHAR(20)          DEFAULT '',
  NUMERIC     TINYINT(1)  NOT NULL,
  GENERIC     TINYINT(1)  NOT NULL
  COMMENT '是否是SKU通用属性',
  SEARCHING   TINYINT(1)  NOT NULL
  COMMENT '是否用于搜索过滤',
  SEGMENTS    VARCHAR(200)         DEFAULT '',
  PRIMARY KEY (ID)
);

CREATE TABLE HM_SPU (
  ID               BIGINT(20)   NOT NULL AUTO_INCREMENT,
  BRAND_ID         BIGINT(20)   NOT NULL,
  TITLE            VARCHAR(250) NOT NULL,
  SUB_TITLE        VARCHAR(250) NOT NULL DEFAULT '',
  SALEABLE         TINYINT(1)   NOT NULL DEFAULT '1',
  VALID            TINYINT(1)   NOT NULL DEFAULT '1',
  CATEGORY_ID1     BIGINT(20)   NOT NULL
  COMMENT '一级类目ID',
  CATEGORY_ID2     BIGINT(20)   NOT NULL
  COMMENT '二级类目ID',
  CATEGORY_ID3     BIGINT(20)   NOT NULL
  COMMENT '三级类目ID',
  CREATE_TIME      DATETIME     NOT NULL,
  LAST_UPDATE_TIME DATETIME     NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE HM_SPU_DETAIL (
  ID            BIGINT(20)    NOT NULL AUTO_INCREMENT,
  SPU_ID        BIGINT(20)    NOT NULL,
  DESCRIPTION   TEXT COMMENT '描述',
  GENERIC_SPEC  VARCHAR(3000) NOT NULL
  COMMENT '通用规格参数数据',
  SPECIAL_SPEC  VARCHAR(1000) NOT NULL
  COMMENT '特有规格参数及可选信息，JSON格式',
  PACKING_LIST  VARCHAR(1000) NOT NULL
  COMMENT '包装清单',
  AFTER_SERVICE VARCHAR(1000) NOT NULL
  COMMENT '售后服务',
  PRIMARY KEY (ID)
);

CREATE TABLE HM_SKU (
  ID               BIGINT(20)   NOT NULL AUTO_INCREMENT,
  SPU_ID           BIGINT(20)   NOT NULL,
  TITLE            VARCHAR(250) NOT NULL,
  IMAGES           VARCHAR(10000)        DEFAULT '',
  PRICE            BIGINT(15)   NOT NULL DEFAULT '0'
  COMMENT '售价，单位为分',
  INDEXES          VARCHAR(100)          DEFAULT ''
  COMMENT '特有规格属性在SPU属性模板中的对应下标组合',
  OWN_SPEC         VARCHAR(1000)         DEFAULT ''
  COMMENT 'SPU特有规格键值对, JSON格式',
  ENABLE           TINYINT(1)   NOT NULL DEFAULT '1',
  CREATE_TIME      DATETIME     NOT NULL,
  LAST_UPDATE_TIME DATETIME     NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE HM_STOCK (
  ID            BIGINT(20) NOT NULL AUTO_INCREMENT,
  SKU_ID        BIGINT(20) NOT NULL,
  SEC_KILL_STOCK INT        NOT NULL DEFAULT '0',
  SEC_KILL_TOTAL INT        NOT NULL DEFAULT '0',
  STOCK         INT        NOT NULL DEFAULT '0',
  PRIMARY KEY (ID)
);