server:
  port: 8091
spring:
  application:
    name: shop-registry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8091/eureka
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000
