server:
  port: 8081
spring:
  application:
    name: item-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8091/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15